    // Datos de los cantos
const songs = [

        {id:1,title: "A la cena del Cordero", subtitle: "Himno lat. «Ad cenam Agni providi»", category: "Eleccion", moments: ["Pascua", "Pentecostés", "Entrada", ""], url: "/cantos/resucito/a/alacenadelcordero.html"},

        {id:2,title: "A la víctima pascual", subtitle: "Secuencia de Pascua - Himno lat. «Victimae paschall laudes» ", category: "Precatecumenado", moments: ["Pascua", "Pentecostés", "Comunión"], url: "/resucito/src/index.html?canto=alavictimapascual"},
        {id:3,title: "A nadie demos ocasión de tropiezo", subtitle: "2ª Corintios 6,3ss", category: "Precatecumenado", moments: ["Nuevo Testamento"], url: "/resucito/src/index.html?canto=anadiedemosocasiondetropiezo"},

        {id:4,title: "A ti levanto mis ojos", subtitle: "Salmo 123 (122)", category: "Precatecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/resucito/a/atilevantomisojos.html"},
        {id:5,title: "A ti, Señor, en mi clamor imploro", subtitle: "Salmo 142 (141)", category: "Precatecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/resucito/a/atisenorenmiclamorimploro.html"},
        {id:6,title: "A ti, Señor, levanto mi alma", subtitle: "Salmo 25 (24)", category: "Precatecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/resucito/a/atisenorlevantomialma.html"},
        {id:7,title: "A ti, Señor, se debe la alabanza en Sión", subtitle: "Salmo 65 (64)", category: "Precatecumenado", moments: ["Cuaresma", "Laudes", "Antiguo Testamento"], url: "/cantos/resucito/a/atisenorsedebelaalabanzaension.html"},
        {id:8,title: "Abbá, Padre", subtitle: "Romanos 8,15–17", category: "Precatecumenado", moments: ["Laudes/Visperas", "Comunión", "Nuevo Testamento"], url: "/cantos/resucito/a/abbapadre.html"},
        {id:9,title: "Abraham", subtitle: "Génesis 18,1–5 – Teofanía de Mambré", category: "Precatecumenado", moments: ["Laudes/Visperas", "Entrada", "Antiguo Testamento"], url: "/cantos/resucito/a/abraham.html"},
        {id:10,title: "Aclamaciones a la oración de los fieles", subtitle: "Respuestas a las oraciones de los fieles, Modelo I, II, III, IV", category: "Liturgia", moments: ["Laudes/Visperas", "Final", "Antiguo Testamento"], url: "/cantos/resucito/liturgia/aclamacionesalaoraciondelosfieles.html"},
        {id:11,title: "Aclamad al Señor", subtitle: "Salmo 100 (99)", category: "Precatecumenado", moments: ["Pascua"], url: "/cantos/resucito/a/aclamadalsenor.html"},
        {id:12,title: "Adónde te escondiste, Amado", subtitle: "Cántico espiritual (San Juan de la Cruz) ", category: "Eleccion", moments: ["Cuaresma", "Laudes", "Antiguo Testamento"], url: "/cantos/resucito/a/adondeteescondisteamado.html"},
        {id:13,title: "Al despertar", subtitle: "Salmo 17 (16) ", category: "Precatecumenado", moments: ["Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/resucito/a/aldespertar.html"},
        {id:14,title: "Alabad al Señor en el cielo", subtitle: "Salmo 148 ", category: "Precatecumenado", moments: ["Navidad", "Niños"], url: "/cantos/resucito/a/alabadalsenorenelcielo.html"},
        {id:15,title: "Alegría, ha nacido el salvador", subtitle: "Villancico (Kiko Argüello)", category: "Precatecumenado", moments: ["Adviento", "Navidad", "Ordinario"], url: "/cantos/resucito/a/alegriahanacidoelsalvador.html"},
        {id:16,title: "Aleluya interleccional", subtitle: "Modelo I, II, III", category: "Liturgia", moments: ["Pascua"], url: "/cantos/resucito/liturgia/aleluyainterleccional.html"},
        {id:17,title: "Aleluya pascual", subtitle: "Apropiado para el tiempo Pascual", category: "Liturgia", moments: ["Pascua", "Laudes", "Final", "Antiguo Testamento"], url: "/cantos/resucito/liturgia/aleluyapascual.html"},
        {id:18,title: "Aleluya, alabad al Señor", subtitle: "Salmo 150", category: "Precatecumenado", moments: ["Pascua", "Niños", "Paz", "Antiguo Testamento"], url: "/cantos/resucito/a/aleluyaalabadalsenor.html"},
        {id:19,title: "Aleluya, bendecid al Señor", subtitle: "Salmo 1.34 (1.33) - Melodía hebraica", category: "Precatecumenado", moments: ["Laudes/Visperas", "Comunión", "Nuevo Testamento"], url: "/cantos/resucito/a/aleluyabendecidalsenor.html"},
        {id:20,title: "Aleluya, ya llegó el reino", subtitle: "Apocalipsis 19,6-9", category: "Precatecumenado", moments: ["Entrada", "Antiguo Testamento"], url: "/cantos/resucito/a/aleluyayallegoelreino.html"},
        {id:21,title: "Alzaos, puertas", subtitle: "Salmo 24 (23)", category: "Precatecumenado", moments: ["Entrada", "Nuevo Testamento"], url: "/cantos/resucito/a/alzaospuertas.html"},
        {id:22,title: "Amén, amén, amén", subtitle: "Apocalipsis 7,12-14 ", category: "Precatecumenado", moments: ["Cuaresma", "Laudes", "Antiguo Testamento", ""], url: "/cantos/resucito/a/amenamenamen.html"},
        {id:23,title: "Amo al Señor", subtitle: "Salmo 116 (114-115)", category: "Precatecumenado", moments: ["Cuaresma"], url: "/cantos/resucito/a/amoalsenor.html"},
        {id:24,title: "Antífona para el Evangelio", subtitle: "Tiempo de Cuaresma", category: "Liturgia", moments: ["Pascua", "Niños", "Fracción del Fracción del Pan", "Antiguo Testamento"], url: "/cantos/resucito/liturgia/antifonaparaelevangelio.html"},
        {id:25,title: "Aquedah", subtitle: "Gn 22,1-19 - Del Targum Neofiti sobre el sacrificio de Isaac", category: "Precatecumenado", moments: ["Pascua", "Pentecostés", "Comunión"], url: "/cantos/resucito/a/aquedah.html"},
        {id:26,title: "Así habla el amén", subtitle: "Ap 3,14-20", category: "Precatecumenado", moments: ["Virgen", "Nuevo Testamento"], url: "/cantos/resucito/a/asihablaelamen.html"},
        {id:27,title: "Ave María I", subtitle: "Lc 1,28ss", category: "Precatecumenado", moments: ["Virgen", "Final", "Nuevo Testamento"], url: "/cantos/resucito/a/avemariai.html"},
        {id:28,title: "Ave María II (1984)", subtitle: "Lc 1,28ss - 1984 ", category: "Precatecumenado", moments: ["Cuaresma", "Laudes", "Antiguo Testamento"], url: "/cantos/resucito/a/avemariaii.html"},
        {id:29,title: "Babilonia criminal", subtitle: "Sal 137 (136)", category: "Precatecumenado", moments: ["Paz", "Comunión", "Final", "Antiguo Testamento"], url: "/cantos/resucito/b/babiloniacriminal.html"},
        {id:30,title: "Balaam", subtitle: "Nm 23,7-24", category: "Precatecumenado", moments: ["Cuaresma", "Laudes", "Antiguo Testamento"], url: "/cantos/resucito/b/balaam.html"},
        {id:31,title: "Bendeciré al Señor en todo tiempo", subtitle: "Sal 34 (33)", category: "Precatecumenado", moments: ["Cuaresma", "Laudes", "Antiguo Testamento"], url: "/cantos/resucito/b/bendecirealsenorentodotiempo.html"},
        {id:32,title: "Bendice, alma mía, a Yahveh", subtitle: "Sal 103 (102)", category: "Precatecumenado", moments: ["Pascua"], url: "/cantos/resucito/b/bendicealmamiaayahveh.html"},
        {id:33,title: "Bendición del agua", subtitle: "De la liturgia bautismal de la Vigilia pascual", category: "Liturgia", moments: [""], url: "/cantos/resucito/liturgia/bendiciondelagua.html"},
        {id:34,title: "Bendita eres tú, María", subtitle: "Lucas 1,42-45", category: "Precatecumenado", moments: ["Penitencial"], url: "/cantos/resucito/b/benditaerestumaria.html"},
        {id:35,title: "Bendito eres, Señor", subtitle: "Daniel 3,52-57", category: "Precatecumenado", moments: ["Virgen", "Entrada", "Final", "Nuevo Testamento"], url: "/cantos/resucito/b/benditoeressenor.html"},
        {id:36,title: "Bendito sea Dios", subtitle: "Efesios 1,3-13", category: "Precatecumenado", moments: ["Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/resucito/b/benditoseadios.html"},
        {id:37,title: "Benedictus", subtitle: "Lucas 1,67-80", category: "Precatecumenado", moments: [""], url: "/cantos/resucito/b/benedictus.html"},
        {id:38,title: "Cantad a Dios", subtitle: "Salmo 67 (68) 2.4-7", category: "Precatecumenado", moments: ["Laudes/Visperas", "Nuevo Testamento"], url: "/cantos/resucito/c/cantadadios.html"},
        {id:39,title: "Cantad al Señor", subtitle: "Salmo 117 (116)", category: "Precatecumenado", moments: ["Cuaresma", "Laudes", "Antiguo Testamento"], url: "/cantos/resucito/c/cantadalsenor.html"},
        {id:40,title: "Cántico de los tres jóvenes", subtitle: "Daniel 3,57-58", category: "Precatecumenado", moments: ["Laudes/Visperas", "Entrada", "Final", "Antiguo Testamento"], url: "/cantos/resucito/c/canticodelostresjovenes.html"},
        {id:41,title: "Canto de Moisés", subtitle: "Éxodo 15,1-18", category: "Precatecumenado", moments: ["Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/resucito/c/cantodemoises.html"},
        {id:42,title: "Caritas Christi urget nos", subtitle: "2ª Corintios 5,14.15.17.21", category: "Precatecumenado", moments: ["Pascua", "Antiguo Testamento"], url: "/cantos/resucito/c/caritaschristiurgetnos.html"},
        {id:43,title: "Carmen 63 - (Están rotas mis ataduras )", subtitle: "(Rabindranath Tagore)*", category: "Precatecumenado", moments: ["Nuevo Testamento"], url: "/cantos/resucito/c/carmen63.html"},
        {id:44,title: "Celebración penitencial", subtitle: "Acción de gracias", category: "Liturgia", moments: ["Nuevo Testamento"], url: "/cantos/resucito/liturgia/celebracionpenitencial.html"},
        {id:45,title: "Como condenados a muerte", subtitle: "1ª Corintios 4,9-13", category: "Precatecumenado", moments: ["Pascua", "Comunión"], url: "/cantos/resucito/c/comocondenadosamuerte.html"},
        {id:46,title: "Como destila la miel", subtitle: "Oda XL de Salomón", category: "Eleccion", moments: ["Laudes/Visperas", "Entrada", "Comunión"], url: "/cantos/resucito/c/comodestilalamiel.html"},
        {id:47,title: "Como el impulso que siente la ira", subtitle: "Oda VII de Salomón", category: "Catecumenado", moments: ["Paz", "Antiguo Testamento"], url: "/cantos/resucito/c/comoelimpulsoquesientelaira.html"},
        {id:48,title: "Cómo es maravilloso", subtitle: "Salmo 133 (132)", category: "Precatecumenado", moments: ["Cuaresma", "Laudes", "Antiguo Testamento"], url: "/cantos/resucito/c/comoesmaravilloso.html"},
        {id:49,title: "Como la cierva", subtitle: "Salmo 42-43 (41-42)", category: "Precatecumenado", moments: ["Pascua", "Comunión", "Antiguo Testamento"], url: "/cantos/resucito/c/comolacierva.html"},
        {id:50,title: "Como lirio entre los cardos", subtitle: "Cantar de los cantares 1,13ss ", category: "Eleccion", moments: ["Adviento", "Entrada", "Paz", "Final", "Antiguo Testamento"], url: "/cantos/resucito/c/comolirioentreloscardos.html"},
        {id:51,title: "Como oveja que ve", subtitle: "Kontáklon (Romano el Meloda)", category: "Precatecumenado", moments: ["Fracción del Pan"], url: "/cantos/resucito/c/comoovejaqueve.html"},
        {id:52,title: "Consolad a mi pueblo", subtitle: "Isaías 40,1-11 - Melodía hebraica ", category: "Precatecumenado", moments: [""], url: "/cantos/resucito/c/consoladamipueblo.html"},
        {id:53,title: "Cordero de Dios", subtitle: "Después de la consagración", category: "Liturgia", moments: ["Entrada"], url: "/cantos/resucito/liturgia/corderodedios.html"},
        {id:54,title: "Credo", subtitle: "Símbolo Apostólico", category: "Liturgia", moments: ["Pascua", "Laudes", "Comunión", "Antiguo Testamento"], url: "/cantos/resucito/liturgia/credo.html"},
        {id:55,title: "Cristo es la luz", subtitle: "Himno - Juan 8,12; 14,6", category: "Precatecumenado", moments: ["Cuaresma", "Entrada", "Final", "Antiguo Testamento"], url: "/cantos/resucito/c/cristoeslaluz.html"},
        {id:56,title: "Cuando dormía", subtitle: "Cantar de los Cantares 5,2ss ", category: "Catecumenado", moments: ["Pascua", "Laudes", "Antiguo Testamento"], url: "/cantos/resucito/c/cuandodormia.html"},
        {id:57,title: "Cuando el Señor", subtitle: "Salmo 126 (125)", category: "Precatecumenado", moments: ["Pascua", "Paz", "Final"], url: "/cantos/resucito/c/cuandoelsenor.html"},
        {id:58,title: "Cuando Israel salió de Egipto", subtitle: "Salmo 114 (113)", category: "Precatecumenado", moments: ["Pascua", "Paz"], url: "/cantos/resucito/c/cuandoisraelsaliodeegipto.html"},
        {id:59,title: "Dayenú", subtitle: "De la Hagadá de Pésaj hebrea", category: "Precatecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/resucito/d/dayenu.html"},
        {id:60,title: "De Profundis", subtitle: "Salmo 130 (129)", category: "Precatecumenado", moments: ["Adviento", "Virgen", "Antiguo Testamento"], url: "/cantos/resucito/d/deprofundis.html"},
        {id:61,title: "Débora", subtitle: "Jueces 5", category: "Catecumenado", moments: ["Cuaresma", "Entrada", "Antiguo Testamento"], url: "/cantos/resucito/d/debora.html"},
        {id:62,title: "Decidle a los de corazón cansado", subtitle: "Isaías 35,4ss", category: "Precatecumenado", moments: ["Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/resucito/d/decidlealosdecorazoncansado.html"},
        {id:63,title: "Delante de los ángeles", subtitle: "Salmo 138 (137)", category: "Precatecumenado", moments: ["Final", "Nuevo Testamento"], url: "/cantos/resucito/d/delantedelosangeles.html"},
        {id:64,title: "Día de reposo", subtitle: "Juan 8,52", category: "Precatecumenado", moments: ["Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/resucito/d/diadereposo.html"},
        {id:65,title: "Dice el Señor a mi Señor", subtitle: "Salmo 110 (109)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/resucito/d/diceelsenoramisenor.html"},
        {id:66,title: "Dichoso el hombre", subtitle: "Salmo 1", category: "Precatecumenado", moments: ["Pascua", "Entrada", "Nuevo Testamento"], url: "/cantos/resucito/d/dichosoelhombre.html"},
        {id:67,title: "El combate escatológico", subtitle: "Apocalipsis 19,11-20", category: "Precatecumenado", moments: ["Laudes/Visperas", "Final", "Antiguo Testamento", "Nuevo Testamento"], url: "/cantos/resucito/e/elcombateescatologico.html"},
        {id:68,title: "El Espíritu del Señor está sobre mí", subtitle: "Lucas 4,18 – Isaías 61,1-3", category: "Precatecumenado", moments: ["Pascua", "Comunión", "Antiguo Testamento"], url: "/cantos/resucito/e/elespiritudelsenorestasobremi.html"},
        {id:69,title: "El jacal de los pastores", subtitle: "Cantar de los Cantares 1,2-8", category: "Precatecumenado", moments: ["Fracción del Pan", "Antiguo Testamento"], url: "/cantos/resucito/e/eljacaldelospastores.html"},
        {id:70,title: "El lagarero", subtitle: "Isaías 63,1-6", category: "Precatecumenado", moments: ["Comunión", "Nuevo Testamento"], url: "/cantos/resucito/e/ellagarero.html"},
        {id:71,title: "El Mesías león", subtitle: "Comentario al Apocalipsis (Victorino de Pettau)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/resucito/e/elmesiasleon.html"},
        {id:72,title: "El mismo Dios", subtitle: "2 Corintios 4,6-12", category: "Catecumenado", moments: ["Navidad", "Antiguo Testamento"], url: "/cantos/resucito/e/elmismodios.html"},
        {id:73,title: "El necio piensa que Dios no existe", subtitle: "Salmo 14 (13)", category: "Precatecumenado", moments: ["Entrada", "Nuevo Testamento"], url: "/cantos/resucito/e/elneciopiensaquediosnoexiste.html"},
        {id:74,title: "El pueblo que caminaba en las tinieblas", subtitle: "Isaías 9,1-5", category: "Precatecumenado", moments: ["Adviento", "Entrada", "Antiguo Testamento"], url: "/cantos/resucito/e/elpuebloquecaminabaenlastinieblas.html"},
        {id:75,title: "El sembrador", subtitle: "Marcos 4,3ss", category: "Catecumenado", moments: ["Comunión", "Antiguo Testamento"], url: "/cantos/resucito/e/elsembrador.html"},
        {id:76,title: "El Señor anuncia una noticia", subtitle: "Salmo 68 (67)", category: "Precatecumenado", moments: ["Fracción del Pan", "Antiguo Testamento"], url: "/cantos/resucito/e/elsenoranunciaunanoticia.html"},
        {id:77,title: "El Señor es mi pastor", subtitle: "Salmo 23 (22)", category: "Precatecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/resucito/e/elsenoresmipastor.html"},
        {id:78,title: "El Señor me ha dado", subtitle: "Isaías 50,4-10  - Tercer canto del Siervo de Yahveh", category: "Precatecumenado", moments: ["Entrada", "Comunión", "Nuevo Testamento"], url: "/cantos/resucito/e/elsenormehadado.html"},
        {id:79,title: "Elí, Elí, lamá sabactaní", subtitle: "Salmo 22 (21)", category: "Precatecumenado", moments: ["Fracción del Pan"], url: "/cantos/resucito/e/elielilamasabactani.html"},
        {id:80,title: "En medio de aquel gentío", subtitle: "Lucas 8,42b-48", category: "Precatecumenado", moments: ["Laudes/Visperas", "Fracción del Pan", "Nuevo Testamento"], url: "/cantos/resucito/e/enmediodeaquelgentio.html"},
        {id:81,title: "En una noche oscura", subtitle: "Subida al Monte Carmelo – San Juan de la Cruz", category: "Precatecumenado", moments: ["Entrada", "Final", "Antiguo Testamento"], url: "/cantos/resucito/e/enunanocheoscura.html"},
        {id:82,title: "Eres digno de tomar el libro", subtitle: "Apocalipsis 5,9ss", category: "Precatecumenado", moments: ["Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/resucito/e/eresdignodetomarellibro.html"},
        {id:83,title: "Eres hermoso", subtitle: "Salmo 45 (44) ", category: "Precatecumenado", moments: ["Entrada", "Fracción del Pan", "Antiguo Testamento"], url: "/cantos/resucito/e/ereshermoso.html"},
        {id:84,title: "Es paciente", subtitle: "Himno al Espíritu Santo (Kiko Argüello) ", category: "Precatecumenado", moments: [""], url: "/cantos/resucito/e/espaciente.html"},
        {id:85,title: "Escóndeme en lo oculto de tu tienda", subtitle: "Salmo 27 (26)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/resucito/e/escondemeenloocultodetutienda.html"},
        {id:86,title: "Escuchad, islas lejanas", subtitle: "Isaias 49,1-16 - Segundo canto de Siervo de Yahveh", category: "Precatecumenado", moments: ["Pascua", "Fracción del Fracción del Pan", "Comunión", "Nuevo Testamento"], url: "/cantos/resucito/e/escuchadislaslejanas.html"},
        {id:87,title: "Éste es el día en que actuó el Señor", subtitle: "Sal 118 (117)", category: "Precatecumenado", moments: ["Paz"], url: "/cantos/resucito/e/esteeseldiaenqueactuoelsenor.html"},
        {id:88,title: "Este es el mandamiento mío", subtitle: "Jn 15,12ss", category: "Precatecumenado", moments: ["Cuaresma", "Fracción del Pan"], url: "/cantos/resucito/e/esteeselmandamientomio.html"},
        {id:89,title: "Evenu shalom alejem", subtitle: "Melodía hebraica", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/resucito/e/evenushalomalejem.html"},
        {id:90,title: "Extiendo mis manos", subtitle: "Oda XXVII de Salomón", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/resucito/e/extiendomismanos.html"},
        {id:91,title: "Exultad, justos, en el Señor", subtitle: "Sal 33 (32)", category: "Precatecumenado", moments: ["Pascua"], url: "/cantos/resucito/e/exultadjustosenelsenor.html"},
        {id:92,title: "Felicidad para el hombre", subtitle: "Sal 128 (127)", category: "Precatecumenado", moments: ["Paz", "Comunión", "Final", "Antiguo Testamento"], url: "/cantos/resucito/f/felicidadparaelhombre.html"},
        {id:93,title: "Gloria a Dios en lo alto del cielo", subtitle: "Himno Litúrgico", category: "Liturgia", moments: ["Entrada", "Antiguo Testamento"], url: "/cantos/resucito/liturgia/gloriaadiosenloaltodelcielo.html"},
        {id:94,title: "Gracias a Yahveh", subtitle: "Sal 136 (135) - Melodía hebraica", category: "Precatecumenado", moments: ["Entrada"], url: "/cantos/resucito/g/graciasayahveh.html"},
        {id:95,title: "Gritad jubilosos", subtitle: "Isaías 12,1ss", category: "Precatecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/resucito/g/gritadjubilosos.html"},
        {id:96,title: "Hacia ti, morada santa", subtitle: "Himno procesional eucarístico (Kiko Argüello)", category: "Precatecumenado", moments: ["Fracción del Pan", "Antiguo Testamento"], url: "/cantos/resucito/h/haciatimoradasanta.html"},
        {id:97,title: "Hasta cuándo", subtitle: "Sal 13 (12)", category: "Precatecumenado", moments: ["Cuaresma", "Pascua", "Laudes/Visperas"], url: "/cantos/resucito/h/hastacuando.html"},
        {id:98,title: "He aquí mi siervo", subtitle: "Isaías 42,1-4; Mateo 12,18-21 - Primer canto de Siervo de Yahveh", category: "Precatecumenado", moments: ["Adviento", "Nuevo Testamento"], url: "/cantos/resucito/h/heaquimisiervo.html"},
        {id:99,title: "He aquí que nuestro espejo es el Señor", subtitle: "Oda XIII de Salomón", category: "Catecumenado", moments: ["Adviento", "Cuaresma", "Antiguo Testamento"], url: "/cantos/resucito/h/heaquiquenuestroespejoeselsenor.html"},
        {id:100,title: "He aquí que vengo presto", subtitle: "Apocalipsis 22,12-16", category: "Precatecumenado", moments: ["Pascua", "Comunión", "Antiguo Testamento"], url: "/cantos/resucito/h/heaquiquevengopresto.html"},
        {id:101,title: "He esperado en el Señor", subtitle: "Salmo 40 (39)", category: "Precatecumenado", moments: ["Cuaresma", "Nuevo Testamento"], url: "/cantos/resucito/h/heesperadoenelsenor.html"},
        {id:102,title: "Hermosa eres, amiga mía", subtitle: "Cantar de los cantares 6-7", category: "Eleccion", moments: ["Pascua"], url: "/cantos/resucito/h/hermosaeresamigamia.html"},
        {id:103,title: "Hijas de Jerusalén", subtitle: "Lucas 23,28-46", category: "Precatecumenado", moments: ["Pentecostés", "Comunión", "Nuevo Testamento"], url: "/cantos/resucito/h/hijasdejerusalen.html"},
        {id:104,title: "Himno a Cristo luz", subtitle: "Himno vespertino (San Gregorio Nacianceno)", category: "Precatecumenado", moments: ["Laudes/Visperas", "Entrada"], url: "/cantos/resucito/h/himnoacristoluz.html"},
        {id:105,title: "Himno a la caridad", subtitle: "1 Corintios 13,1-7", category: "Precatecumenado", moments: ["Cuaresma", "Fracción del Fracción del Pan", "Nuevo Testamento"], url: "/cantos/resucito/h/himnoalacaridad.html"},
        {id:106,title: "Himno a la cruz gloriosa", subtitle: "Homilía La Santa Pascua (Anónimo s. II)", category: "Catecumenado", moments: ["Adviento"], url: "/cantos/resucito/h/himnoalacruzgloriosa.html"},
        {id:107,title: "Himno a la kenosis", subtitle: "Filipenses 2,1-11", category: "Precatecumenado", moments: ["Laudes/Visperas"], url: "/cantos/resucito/h/himnoalakenosis.html"},
        {id:108,title: "Himno de Adviento", subtitle: "Himno lat. «Vox clara ecce Intonat»", category: "Precatecumenado", moments: ["Pascua", "Laudes"], url: "/cantos/resucito/h/himnodeadviento.html"},
        {id:109,title: "Himno de la Ascensión", subtitle: "Himno de Laudes del tiempo Pascual, de la Ascensión a Pentecostés  / Himno de la liturgia de las horas ", category: "Precatecumenado", moments: ["Pascua", "Comunión", "Final", "Antiguo Testamento"], url: "/cantos/resucito/h/himnodelaascension.html"},
        {id:110,title: "Himno de Pascua", subtitle: "Himno lat. «Aurora lucis rutiiat»", category: "Precatecumenado", moments: ["Final", "Nuevo Testamento"], url: "/cantos/resucito/h/himnodepascua.html"},
        {id:111,title: "Huye, amado mío", subtitle: "Cantar de los Cantares 8,10-14", category: "Precatecumenado", moments: ["Cuaresma"], url: "/cantos/resucito/h/huyeamadomio.html"},
        {id:112,title: "Id y anunciad a mis hermanos", subtitle: "Mateo 28,10.16-20", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/resucito/i/idyanunciadamishermanos.html"},
        {id:113,title: "Improperios", subtitle: "Adoración de la santa Cruz el Viernes santo", category: "Precatecumenado", moments: ["Cuaresma", "Paz", "Antiguo Testamento"], url: "/cantos/resucito/i/improperios.html"},
        {id:114,title: "Jacob", subtitle: "Genesis 32,23-29 ", category: "Catecumenado", moments: ["Nuevo Testamento"], url: "/cantos/resucito/j/jacob.html"},
        {id:115,title: "Jerusalén reconstruida", subtitle: "Tobias 13,11-17", category: "Precatecumenado", moments: ["Navidad", "Virgen", "Nuevo Testamento"], url: "/cantos/resucito/j/jerusalenreconstruida.html"},
        {id:116,title: "Jesús recorría todas las ciudades", subtitle: "Mateo 9,35ss; 10 ", category: "Precatecumenado", moments: ["Cuaresma"], url: "/cantos/resucito/j/jesusrecorriatodaslasciudades.html"},
        {id:117,title: "La cordera de Dios", subtitle: "Mateo 1,18s; 2,13s.18", category: "Precatecumenado", moments: ["Laudes/Visperas", "Comunión"], url: "/cantos/resucito/l/lacorderadedios.html"},
        {id:118,title: "La espada", subtitle: "Ezequiel 21,14-22", category: "Precatecumenado", moments: ["Virgen"], url: "/cantos/resucito/l/laespada.html"},
        {id:119,title: "La marcha es dura", subtitle: "Espiritual negro «Go down, Moses»", category: "Precatecumenado", moments: ["Final", "Nuevo Testamento"], url: "/cantos/resucito/l/lamarchaesdura.html"},
        {id:120,title: "La paloma voló", subtitle: "Oda XXIV de Salomón", category: "Eleccion", moments: ["Comunión", "Antiguo Testamento"], url: "/cantos/resucito/l/lapalomavolo.html"},
        {id:121,title: "La Salve", subtitle: "Himno lat. «Salve Regina»", category: "Precatecumenado", moments: ["Cuaresma", "Laudes", "Nuevo Testamento"], url: "/cantos/resucito/l/lasalve.html"},
        {id:122,title: "La siega de las naciones", subtitle: "Juan 4,31-38", category: "Precatecumenado", moments: [""], url: "/cantos/resucito/l/lasiegadelasnaciones.html"},
        {id:123,title: "La voz de mi amado", subtitle: "Cantar de los Cantares 2,8-17", category: "Precatecumenado", moments: [""], url: "/cantos/resucito/l/lavozdemiamado.html"},
        {id:124,title: "Las armas de la luz", subtitle: "cf Efesios 6,11.ss", category: "Precatecumenado", moments: [""], url: "/cantos/resucito/l/lasarmasdelaluz.html"},
        {id:125,title: "Lauda Sión", subtitle: "Secuencia del Corpus Christi (Santo Tomas de Aquino) ", category: "Precatecumenado", moments: [""], url: "/cantos/resucito/l/laudasion.html"},
        {id:126,title: "Letanías de los santos", subtitle: "De la liturgia bautismal de la Vigilia pascual", category: "Liturgia", moments: [""], url: "/cantos/resucito/liturgia/letaniasdelossantos.html"},
        {id:127,title: "Letanías penitenciales I", subtitle: "Letanía para la Celebración Penitencial – modelo abreviado", category: "Liturgia", moments: ["Cuaresma", "Laudes", "Entrada", "Antiguo Testamento"], url: "/cantos/resucito/liturgia/letaniaspenitencialesi.html"},
        {id:128,title: "Letanías penitenciales II", subtitle: "Letanía para la Celebración Penitencial", category: "Liturgia", moments: ["Cuaresma", "Laudes", "Entrada"], url: "/cantos/resucito/liturgia/letaniaspenitencialesii.html"},
        {id:129,title: "Levanto mis ojos a los montes", subtitle: "Sal 121 (120)", category: "Precatecumenado", moments: ["Adviento", "Pentecostés", "Final", "Nuevo Testamento"], url: "/cantos/resucito/l/levantomisojosalosmontes.html"},
        {id:131,title: "Llegue hasta tu presencia mi clamor", subtitle: "Sal 119 (118)", category: "Precatecumenado", moments: ["Virgen", "Laudes", "Nuevo Testamento"], url: "/cantos/resucito/l/lleguehastatupresenciamiclamor.html"},
        {id:132,title: "Llévame al cielo", subtitle: "Filipenses 1,23", category: "Precatecumenado", moments: ["Virgen"], url: "/cantos/resucito/l/llevamealcielo.html"},
        {id:133,title: "Magníficat", subtitle: "Lucas 1,46-55", category: "Precatecumenado", moments: ["Virgen", "Entrada", "Nuevo Testamento"], url: "/cantos/resucito/m/magnificat.html"},
        {id:134,title: "María de Jasna Göra", subtitle: "Himno a la Virgen de Jasna Göra, Częstochowa Polonia (Kiko Argüello) ", category: "Precatecumenado", moments: ["Virgen"], url: "/cantos/resucito/m/mariadejasnagöra.html"},
        {id:135,title: "María, casa de bendición", subtitle: "Juan 2,1–11 – Las Bodas de Caná", category: "Precatecumenado", moments: ["Cuaresma", "Virgen", "Nuevo Testamento"], url: "/cantos/resucito/m/mariacasadebendicion.html"},
        {id:136,title: "María, madre de la Iglesia", subtitle: "Juan 19,26-34", category: "Precatecumenado", moments: ["Cuaresma", "Virgen"], url: "/cantos/resucito/m/mariamadredelaiglesia.html"},
        {id:137,title: "María, madre del camino ardiente", subtitle: "Himno a la Virgen del Tercer Milenio (Kiko Argüello)", category: "Precatecumenado", moments: ["Adviento", "Entrada", "Antiguo Testamento"], url: "/cantos/resucito/m/mariamadredelcaminoardiente.html"},
        {id:138,title: "María, pequeña María", subtitle: "Himno a la Virgen María (Kiko Argüello)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/resucito/m/mariapequenamaria.html"},
        {id:139,title: "Me enseñarás el camino de la vida", subtitle: "Sal 16 (15)", category: "Precatecumenado", moments: ["Pascua", "Comunión", "Antiguo Testamento"], url: "/cantos/resucito/m/meensenaraselcaminodelavida.html"},
        {id:140,title: "Me has seducido, Señor", subtitle: "Jeremias 20,7-18", category: "Precatecumenado", moments: ["Paz", "Antiguo Testamento"], url: "/cantos/resucito/m/mehasseducidosenor.html"},
        {id:141,title: "Me robaste el corazón", subtitle: "Cantar de los cantares 4,9 - 5,1", category: "Eleccion", moments: ["Cuaresma", "Laudes", "Antiguo Testamento"], url: "/cantos/resucito/m/merobasteelcorazon.html"},
        {id:142,title: "Mirad qué estupendo", subtitle: "Sal 133 (132)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/resucito/m/miradqueestupendo.html"},
        {id:143,title: "Misericordia mía, misericordia", subtitle: "Sal 51 (50)", category: "Precatecumenado", moments: ["Pascua", "Comunión", "Nuevo Testamento"], url: "/cantos/resucito/m/misericordiamiamisericordia.html"},
        {id:144,title: "Misericordia, Dios mío", subtitle: "Sal 51(50)", category: "Precatecumenado", moments: ["Nuevo Testamento"], url: "/cantos/resucito/m/misericordiadiosmio.html"},
        {id:145,title: "Mucho me han perseguido", subtitle: "Sal 129 (128)", category: "Precatecumenado", moments: ["Fracción del Pan", "Antiguo Testamento"], url: "/cantos/resucito/m/muchomehanperseguido.html"},
        {id:146,title: "Ninguno puede servir a dos señores", subtitle: "Mateo 6,24-33 ", category: "Catecumenado", moments: ["Comunión", "Nuevo Testamento"], url: "/cantos/resucito/n/ningunopuedeserviradossenores.html"},
        {id:147,title: "No está aquí, resucitó", subtitle: "Mateo 28,1-8", category: "Precatecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/resucito/n/noestaaquiresucito.html"},
        {id:148,title: "No hay en él parecer", subtitle: "Isaías 53,2ss - Cuarto canto del Siervo de Yahveh", category: "Precatecumenado", moments: ["Pascua", "Nuevo Testamento"], url: "/cantos/resucito/n/nohayenelparecer.html"},
        {id:149,title: "No resistáis al mal", subtitle: "Mateo 5,38ss", category: "Catecumenado", moments: ["Adviento"], url: "/cantos/resucito/n/noresistaisalmal.html"},
        {id:150,title: "No sufras por los malvados", subtitle: "Sal 37 (36)", category: "Catecumenado", moments: ["Antiguo Testamento"], url: "/cantos/resucito/n/nosufrasporlosmalvados.html"},
        {id:151,title: "Noli me tangere", subtitle: "Juan 20,15-17", category: "Precatecumenado", moments: ["Adviento", "Laudes", "Antiguo Testamento"], url: "/cantos/resucito/n/nolimetangere.html"},
        {id:152,title: "Oh cielos, lloved de lo alto", subtitle: "Isaías 45,8", category: "Precatecumenado", moments: ["Cuaresma", "Fracción del Pan", "Comunión"], url: "/cantos/resucito/o/ohcieloslloveddeloalto.html"},
        {id:153,title: "Oh Dios, por tu nombre sálvame", subtitle: "Sal 54 (53)", category: "Precatecumenado", moments: ["Pascua", "Nuevo Testamento"], url: "/cantos/resucito/o/ohdiosportunombresalvame.html"},
        {id:154,title: "Oh Dios, tú eres mi Dios", subtitle: "Sal 63 (62)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/resucito/o/ohdiostueresmidios.html"},
        {id:155,title: "Oh Jesús, amor mío", subtitle: "(Kiko Argüello)", category: "Precatecumenado", moments: ["Laudes/Visperas", "Entrada", "Comunión", "Antiguo Testamento"], url: "/cantos/resucito/o/ohjesusamormio.html"},
        {id:156,title: "Oh muerte, ¿dónde está tu victoria?", subtitle: "1 Corintios 15", category: "Precatecumenado", moments: ["Entrada", "Antiguo Testamento"], url: "/cantos/resucito/o/ohmuerte¿dondeestatuvictoria?.html"},
        {id:157,title: "Oh Señor, mi corazón ya no es ambicioso", subtitle: "Sal 131 (130)", category: "Catecumenado", moments: [""], url: "/cantos/resucito/o/ohsenormicorazonyanoesambicioso.html"},
        {id:158,title: "Oh Señor, nuestro Dios", subtitle: "Salmo 8", category: "Precatecumenado", moments: ["Virgen"], url: "/cantos/resucito/o/ohsenornuestrodios.html"},
        {id:159,title: "Os tomaré de entre las naciones", subtitle: "Ezequiel 36,24-28", category: "Precatecumenado", moments: ["Pentecostés", "Comunión"], url: "/cantos/resucito/o/ostomaredeentrelasnaciones.html"},
        {id:160,title: "Padre nuestro", subtitle: "Tiempo de la Elección", category: "Liturgia", moments: [""], url: "/cantos/resucito/liturgia/padrenuestro.html"},
        {id:161,title: "Paloma incorrupta", subtitle: "Kontákion (Romano el Meloda)", category: "Precatecumenado", moments: [""], url: "/cantos/resucito/p/palomaincorrupta.html"},
        {id:162,title: "Pentecostés", subtitle: "Hchos de los Apostoles 2,1-13 ", category: "Precatecumenado", moments: [""], url: "/cantos/resucito/p/pentecostes.html"},
        {id:163,title: "Plegaria Eucarística II Modelo I", subtitle: "Modelo I", category: "Liturgia", moments: [""], url: "/cantos/resucito/liturgia/plegariaeucaristicaiimodeloip1.html"},
        {id:164,title: "Plegaria Eucarística II Modelo II", subtitle: "Modelo II (1987)", category: "Liturgia", moments: [""], url: "/cantos/resucito/liturgia/plegariaeucaristicaiimodeloii.html"},
        {id:165,title: "Plegaria Eucarística IV  1988", subtitle: "(1988)", category: "Liturgia", moments: [""], url: "/cantos/resucito/liturgia/plegariaeucaristicaiv1988.html"},
        {id:166,title: "Por el amor de mis amigos", subtitle: "Sal 122 (121) - Melodía hebraica ", category: "Precatecumenado", moments: [""], url: "/cantos/resucito/p/porelamordemisamigos.html"},
        {id:167,title: "Por qué esta noche es diferente", subtitle: "Haggadá de Pesaj - Melodía hebraica", category: "Precatecumenado", moments: [""], url: "/cantos/resucito/p/porqueestanocheesdiferente.html"},
        {id:168,title: "Por qué las gentes conjuran", subtitle: "Salmo 2", category: "Precatecumenado", moments: [""], url: "/cantos/resucito/p/porquelasgentesconjuran.html"},
        {id:169,title: "Porque mi yugo es suave", subtitle: "Mateo 11,28ss", category: "Precatecumenado", moments: [""], url: "/cantos/resucito/p/porquemiyugoessuave.html"},
        {id:170,title: "Prefacio para Adviento y Navidad", subtitle: "Prefacio IV de Adviento*", category: "Liturgia", moments: ["Paz", "Antiguo Testamento"], url: "/cantos/resucito/liturgia/prefacioparaadvientoynavidad.html"},
        {id:171,title: "Prefacio para el tiempo Pascual", subtitle: "Prefacio I de Pascua*", category: "Liturgia", moments: ["Pascua", "Niños", "Paz"], url: "/cantos/resucito/liturgia/prefacioparaeltiempopascual.html"},
        {id:172,title: "Pregón Pascual", subtitle: "«Exsultet»", category: "Liturgia", moments: ["Cuaresma", "Laudes", "Antiguo Testamento"], url: "/cantos/resucito/liturgia/pregonpascual.html"},
        {id:174,title: "Qué amables son tus moradas", subtitle: "Sal 84 (83)", category: "Precatecumenado", moments: ["Cuaresma", "Laudes", "Nuevo Testamento"], url: "/cantos/resucito/q/queamablessontusmoradas.html"},
        {id:175,title: "Qué estupendo, qué alegría", subtitle: "Sal 133 (132)", category: "Precatecumenado", moments: ["Adviento", "Navidad"], url: "/cantos/resucito/q/queestupendoquealegria.html"},
        {id:176,title: "Quién es ésta que sube del desierto", subtitle: "Cantar de los Cantares 8,5-7", category: "Precatecumenado", moments: ["Pascua"], url: "/cantos/resucito/q/quienesestaquesubedeldesierto.html"},
        {id:177,title: "Quién nos separará", subtitle: "Romanos 8,34-39", category: "Precatecumenado", moments: ["Pascua"], url: "/cantos/resucito/q/quiennosseparara.html"},
        {id:178,title: "Quiero andar, madre, a Jerusalén", subtitle: "Canto sefardí", category: "Precatecumenado", moments: ["Pascua"], url: "/cantos/resucito/q/quieroandarmadreajerusalen.html"},
        {id:179,title: "Quiero cantar", subtitle: "Sal 57 (56)", category: "Precatecumenado", moments: ["Entrada", "Antiguo Testamento"], url: "/cantos/resucito/q/quierocantar.html"},
        {id:180,title: "Resucitó", subtitle: "(Kiko Argüello)", category: "Precatecumenado", moments: ["Paz", "Antiguo Testamento"], url: "/cantos/resucito/r/resucito.html"},
        {id:181,title: "Resurrexit", subtitle: "Juan 11,25s", category: "Precatecumenado", moments: ["Comunión", "Final", "Antiguo Testamento"], url: "/cantos/resucito/r/resurrexit.html"},
        {id:182,title: "Salmodia para el evangelio", subtitle: "Juan 3,11-20 ", category: "Liturgia", moments: ["Laudes/Visperas", "Comunión", "Nuevo Testamento"], url: "/cantos/resucito/liturgia/salmodiaparaelevangelio.html"},
        {id:183,title: "Salmodia para el rosario", subtitle: "Santo Rosario", category: "Liturgia", moments: ["Final"], url: "/cantos/resucito/liturgia/salmodiaparaelrosario.html"},
        {id:184,title: "Salmodia para el Salmo responsorial", subtitle: "Modelo I, II, III", category: "Liturgia", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/resucito/liturgia/salmodiaparaelsalmoresponsorial.html"},
        {id:185,title: "Salmodias para la oración de los fieles", subtitle: "Para las solemnidades", category: "Liturgia", moments: ["Pascua", "Comunión"], url: "/cantos/resucito/liturgia/salmodiasparalaoraciondelosfieles.html"},
        {id:186,title: "Salmodias para laudes", subtitle: "Modelo I, II, III, IV, V", category: "Liturgia", moments: ["Pascua"], url: "/cantos/resucito/liturgia/salmodiasparalaudes.html"},
        {id:187,title: "Salve, reina de los cielos", subtitle: "Himno lat. «Ave, Regina Caelorum»", category: "Precatecumenado", moments: [""], url: "/cantos/resucito/s/salvereinadeloscielos.html"},
        {id:188,title: "Santo Palomeras 65", subtitle: "Palomeras 65", category: "Liturgia", moments: [""], url: "/cantos/resucito/liturgia/santopalomeras65.html"},
        {id:189,title: "Santo Melodía hebraica ", subtitle: "Melodía hebraica ", category: "Liturgia", moments: ["Ordinario"], url: "/cantos/resucito/liturgia/santomelodiahebraica.html"},
        {id:190,title: "Santo Palestina 74", subtitle: "Palestina 74", category: "Liturgia", moments: ["Ordinario"], url: "/cantos/resucito/liturgia/santopalestina74.html"},
        {id:191,title: "Santo Roma 77", subtitle: "Roma 77", category: "Liturgia", moments: [""], url: "/cantos/resucito/liturgia/santoroma77.html"},
        {id:192,title: "Santo 1982", subtitle: "1982", category: "Liturgia", moments: [""], url: "/cantos/resucito/liturgia/santo1982.html"},
        {id:193,title: "Santo 1988", subtitle: "1988", category: "Liturgia", moments: ["Virgen", "Final"], url: "/cantos/resucito/liturgia/santo1988.html"},
        {id:194,title: "Se encontraron dos ángeles", subtitle: "Melodía hebraica", category: "Precatecumenado", moments: [""], url: "/cantos/resucito/s/seencontrarondosangeles.html"},
        {id:195,title: "Señor, ayúdame a no dudar de ti", subtitle: "(Kiko Argüello)", category: "Precatecumenado", moments: ["Ordinario"], url: "/cantos/resucito/s/senorayudameanodudardeti.html"},
        {id:196,title: "Señor, no me corrijas en tu cólera", subtitle: "Salmo 6", category: "Precatecumenado", moments: ["Niños", "Paz"], url: "/cantos/resucito/s/senornomecorrijasentucolera.html"},
        {id:197,title: "Señor, tú me escrutas y conoces", subtitle: "Sal 139 (138)", category: "Catecumenado", moments: ["Pentecostés", "Entrada"], url: "/cantos/resucito/s/senortumeescrutasyconoces.html"},
        {id:198,title: "Sermón de la montaña", subtitle: "Lucas 6,20-38", category: "Precatecumenado", moments: [""], url: "/cantos/resucito/s/sermondelamontana.html"},
        {id:199,title: "Shemá Israel", subtitle: "Dt 6,4-9", category: "Catecumenado", moments: ["Cuaresma", "Laudes", "Comunión"], url: "/cantos/resucito/s/shemaisrael.html"},
        {id:200,title: "Shlom lej Mariam", subtitle: "Ave María en arameo antiguo", category: "Precatecumenado", moments: ["Laudes/Visperas", "Antiguo Testamento"], url: "/cantos/resucito/s/shlomlejmariam.html"},
        {id:201,title: "Si el Señor no construye la casa", subtitle: "Sal 127 (126)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/resucito/s/sielsenornoconstruyelacasa.html"},
        {id:202,title: "Si habéis resucitado con Cristo", subtitle: "Colosense 3,1-4", category: "Precatecumenado", moments: ["Comunión", "Nuevo Testamento"], url: "/cantos/resucito/s/sihabeisresucitadoconcristo.html"},
        {id:203,title: "Si hoy escucháis su voz", subtitle: "Sal 95 (94)", category: "Precatecumenado", moments: ["Pentecostés", "Antiguo Testamento"], url: "/cantos/resucito/s/sihoyescuchaissuvoz.html"},
        {id:204,title: "Si me he refugiado en el Señor", subtitle: "Sal 11(10)", category: "Precatecumenado", moments: ["Virgen", "Final"], url: "/cantos/resucito/s/simeherefugiadoenelsenor.html"},
        {id:205,title: "Siéntate solitario y silencioso", subtitle: "Lamentaciones 3", category: "Catecumenado", moments: ["Entrada", "Antiguo Testamento"], url: "/cantos/resucito/s/sientatesolitarioysilencioso.html"},
        {id:206,title: "Sión, madre de todos los pueblos", subtitle: "Sal 87 (86)", category: "Precatecumenado", moments: ["Adviento", "Pascua"], url: "/cantos/resucito/s/sionmadredetodoslospueblos.html"},
        {id:207,title: "Sola a Solo", subtitle: "(Kiko Argüello)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/resucito/s/solaasolo.html"},
        {id:208,title: "Stabat Mater dolorosa", subtitle: "Himno latin", category: "Precatecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/resucito/s/stabatmaterdolorosa.html"},
        {id:209,title: "Suba el Esposo al leño de su tálamo", subtitle: "Himno (San Quodvultdeus)", category: "Eleccion", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/resucito/s/subaelesposoallenodesutalamo.html"},
        {id:210,title: "Sube Dios entre aclamaciones", subtitle: "Sal 47 (46)", category: "Precatecumenado", moments: ["Final", "Antiguo Testamento"], url: "/cantos/resucito/s/subediosentreaclamaciones.html"},
        {id:211,title: "Te Deum", subtitle: "Himno", category: "Liturgia", moments: ["Virgen"], url: "/cantos/resucito/liturgia/tedeum.html"},
        {id:212,title: "Te estoy llamando, Señor", subtitle: "Sal 141 (140)", category: "Precatecumenado", moments: ["Cuaresma", "Virgen"], url: "/cantos/resucito/t/teestoyllamandosenor.html"},
        {id:213,title: "Te he manifestado mi pecado", subtitle: "Sal 32 (31)", category: "Precatecumenado", moments: ["Pascua"], url: "/cantos/resucito/t/tehemanifestadomipecado.html"},
        {id:214,title: "Tú eres mi esperanza, Señor", subtitle: "Oda XXIX de Salomón", category: "Catecumenado", moments: ["Pascua", "Pentecostés", "Paz"], url: "/cantos/resucito/t/tueresmiesperanzasenor.html"},
        {id:215,title: "Tú has cubierto de vergüenza la muerte", subtitle: "Homilía Pascual (Melltón de Sardes)", category: "Precatecumenado", moments: ["Laudes/Visperas"], url: "/cantos/resucito/t/tuhascubiertodevergüenzalamuerte.html"},
        {id:216,title: "Tú que eres fiel", subtitle: "Sal 143 (142)", category: "Precatecumenado", moments: ["Antiguo Testamento"], url: "/cantos/resucito/t/tuqueeresfiel.html"},
        {id:217,title: "Un retoño brota del tronco de Jesé", subtitle: "Isaías 11,1-11", category: "Precatecumenado", moments: ["Cuaresma", "Antiguo Testamento"], url: "/cantos/resucito/u/unretonobrotadeltroncodejese.html"},
        {id:218,title: "Una gran señal", subtitle: "Apocalipsis 12", category: "Precatecumenado", moments: ["Adviento", "Cuaresma"], url: "/cantos/resucito/u/unagransenal.html"},
        {id:219,title: "Urí, urí, urá", subtitle: "Villancico (Kiko Argüello)", category: "Precatecumenado", moments: ["Pascua", "Virgen", "Fracción del Pan"], url: "/cantos/resucito/u/uriuriura.html"},
        {id:220,title: "Vamos ya, pastores", subtitle: "Villancico (Kiko Argüello)", category: "Precatecumenado", moments: ["Cuaresma", "Entrada", "Antiguo Testamento"], url: "/cantos/resucito/v/vamosyapastores.html"},
        {id:221,title: "Ven del Líbano", subtitle: "Cantar de los cantares 4,8ss", category: "Precatecumenado", moments: ["Navidad", "Pentecostés", "Comunión", "Antiguo Testamento"], url: "/cantos/resucito/v/vendellibano.html"},
        {id:222,title: "Ven, Espíritu Santo", subtitle: "Secuencia de Pentecostés - Himno latin. «Veni, Sancte Spiritus»", category: "Precatecumenado", moments: ["Adviento", "Pentecostés", "Virgen", "Nuevo Testamento"], url: "/cantos/resucito/v/venespiritusanto.html"},
        {id:223,title: "Ven, Hijo del Hombre", subtitle: "Apocalipsis 21,17ss", category: "Precatecumenado", moments: ["Navidad", "Niños"], url: "/cantos/resucito/v/venhijodelhombre.html"},
        {id:224,title: "Veni Creator", subtitle: "Himno latin", category: "Precatecumenado", moments: ["Navidad", "Niños"], url: "/cantos/resucito/v/venicreator.html"},
        {id:225,title: "Viene el Señor", subtitle: "Salmo 93 (92) - Apocalipsis 1,5-7", category: "Precatecumenado", moments: ["Entrada", "Antiguo Testamento"], url: "/cantos/resucito/v/vieneelsenor.html"},
        {id:226,title: "Virgen de la maravilla", subtitle: "(Dante Allghlerl)", category: "Precatecumenado", moments: ["Pentecostés"], url: "/cantos/resucito/v/virgendelamaravilla.html"},
        {id:227,title: "Vivid alegres", subtitle: "Filipenses 4,4ss", category: "Precatecumenado", moments: ["Adviento", "Final", "Nuevo Testamento"], url: "/cantos/resucito/v/vividalegres.html"},
        {id:228,title: "Vosotros sois la luz del mundo", subtitle: "Mateo 5,14ss ", category: "Precatecumenado", moments: ["Pentecostés"], url: "/cantos/resucito/v/vosotrossoislaluzdelmundo.html"},
        {id:229,title: "Ya viene mi Dios", subtitle: "Villancico (Kiko Argüello)", category: "Precatecumenado", moments: ["Adviento", "Pentecostés", "Antiguo Testamento", "Nuevo Testamento"], url: "/cantos/resucito/y/yavienemidios.html"},
        {id:230,title: "Yahveh, tú eres mi Dios", subtitle: "Isaías 25,1-8", category: "Precatecumenado", moments: ["Virgen"], url: "/cantos/resucito/y/yahvehtueresmidios.html"},
        {id:231,title: "Yo te amo, Señor", subtitle: "Sal 18 (17)", category: "Precatecumenado", moments: ["Adviento", "Niños", "Nuevo Testamento"], url: "/cantos/resucito/y/yoteamosenor.html"},
        {id:232,title: "Yo vengo a reunir", subtitle: "Isaías 66,18-21", category: "Precatecumenado", moments: ["Nuevo Testamento"], url: "/cantos/resucito/y/yovengoareunir.html"},
        {id:233,title: "Zaqueo", subtitle: "Lucas 19,1-10", category: "Precatecumenado", moments: ["Navidad", "Niños"], url: "/cantos/resucito/z/zaqueo.html"},
        {id:234,title: "Prountuario de Acordes", subtitle: "Notas", category: "Precatecumenado", moments: ["Cuaresma", "Laudes", "Antiguo Testamento"], url: "/cantos/resucito/p/prountuariodeacordes.html"},
        {id:235,title: "Libro de Canto en PDF", subtitle: "Libro de Canto del Camino Neo Catecumenal", category: "Precatecumenado", moments: [""], url: "/cantos/src/doc/resucito.pdf", targetBlank: true }
  
    ];